config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'restaurants#index'
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

    CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

    validates :name, presence: true
    validates :phone_number, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 50}
    validates :address, presence: true
    validates :category, presence: true, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)

        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
        else
            render :new
        end
    end

    private

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :category, :phone_number)
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
    end
    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new(review_params)
        @review.restaurant = @restaurant

        if @review.save
            redirect_to restaurant_path(@restaurant)
        else
            render :new
        end
    end

    private
    
    def review_params
        params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'header'%>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_header.html.erb
<%= link_to  "Home", root_path %>
<%= link_to  "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/index.html.erb
<h1>These are some restaurants 🌈</h1>
<div class="container-sm">
  <% @restaurants.each do |restaurant| %>
    <div class="card">
      <%= link_to  restaurant.name, restaurant_path(restaurant), class: "name-link" %>
      <%= restaurant.category %>
      <%= restaurant.address %>
      <%= restaurant.phone_number %>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :category, "Category" %>
  <%= f.input :category, collection: Restaurant::CATEGORIES%>
  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>
  <%= f.label :phone_number, "Phone number" %>
  <%= f.text_field :phone_number %>
  <%= f.submit "Add new restaurant", class: "btn-primary"%>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%= link_to  "Add a review", new_restaurant_review_path(@restaurant) %>
<div class="container-sm">
  <% @restaurant.reviews.each do |review| %>
    <div class="card">
      <p><%= review.content %></p>
    </div>
  <% end %>
</div>

app/views/reviews/_header.html.erb
<%= link_to  "Home", root_path %>
<%= link_to  "Add a new restaurant", new_restaurant_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :content, "Say something" %>
  <%= f.text_area :content %>
  <%= f.input :rating, label: "Rating" %>
  <%= f.submit %>
<% end %>